//! A disassembler for Lumen chunks (buff8).
//!
//! It renders a [`Chunk`] as a human-readable instruction listing — the same
//! information the VM executes, but legible. This serves two purposes: it is the
//! primary debugging tool while building the compiler ("did I emit the jumps I
//! meant to?"), and it is what `lumen --disassemble script.lm` prints so the
//! generated bytecode can be inspected and explained.
//!
//! Each line shows the instruction's index (the jump-target address space), the
//! source line it came from (`|` when the same as the previous instruction), the
//! opcode name, and a decoded operand. Operands that index the constant pool are
//! shown with the constant's value in `( )` so the listing is self-contained.

use std::fmt::Write;

use crate::chunk::{Chunk, Constant};
use crate::opcode::Instr;

/// Disassemble a whole chunk into a string, prefixed by a `== name ==` header.
pub fn disassemble(chunk: &Chunk, name: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "== {name} ==");
    for i in 0..chunk.code.len() {
        let _ = writeln!(out, "{}", disassemble_instr(chunk, i));
    }
    out
}

/// Format a single instruction at index `idx`, without a trailing newline.
pub fn disassemble_instr(chunk: &Chunk, idx: usize) -> String {
    let line = chunk.lines[idx];
    // Repeat the line number only when it changes, so runs from one source line
    // read as a block.
    let line_col = if idx > 0 && chunk.lines[idx - 1] == line {
        "   |".to_string()
    } else {
        format!("{line:>4}")
    };

    let instr = &chunk.code[idx];
    let body = format_instr(chunk, instr);
    format!("{idx:04} {line_col} {body}")
}

/// Render just the opcode and its operand (no address/line prefix).
fn format_instr(chunk: &Chunk, instr: &Instr) -> String {
    match instr {
        Instr::Constant(i) => format!("Constant      {i:>4} ({})", constant_repr(chunk, *i)),
        Instr::Nil => "Nil".into(),
        Instr::True => "True".into(),
        Instr::False => "False".into(),
        Instr::Pop => "Pop".into(),
        Instr::PopKeepTop(n) => format!("PopKeepTop    {n:>4}"),

        Instr::Neg => "Neg".into(),
        Instr::Not => "Not".into(),
        Instr::Add => "Add".into(),
        Instr::Sub => "Sub".into(),
        Instr::Mul => "Mul".into(),
        Instr::Div => "Div".into(),
        Instr::Mod => "Mod".into(),
        Instr::Eq => "Eq".into(),
        Instr::Ne => "Ne".into(),
        Instr::Lt => "Lt".into(),
        Instr::Le => "Le".into(),
        Instr::Gt => "Gt".into(),
        Instr::Ge => "Ge".into(),

        Instr::GetLocal(s) => format!("GetLocal      {s:>4}"),
        Instr::SetLocal(s) => format!("SetLocal      {s:>4}"),
        Instr::GetGlobal(i) => format!("GetGlobal     {i:>4} ({})", constant_repr(chunk, *i)),
        Instr::SetGlobal(i) => format!("SetGlobal     {i:>4} ({})", constant_repr(chunk, *i)),
        Instr::DefineGlobal(i) => format!("DefineGlobal  {i:>4} ({})", constant_repr(chunk, *i)),
        Instr::GetUpvalue(i) => format!("GetUpvalue    {i:>4}"),
        Instr::SetUpvalue(i) => format!("SetUpvalue    {i:>4}"),
        Instr::CloseUpvalue => "CloseUpvalue".into(),

        Instr::Jump(t) => format!("Jump          -> {t:04}"),
        Instr::JumpIfFalse(t) => format!("JumpIfFalse   -> {t:04}"),
        Instr::JumpIfFalsePeek(t) => format!("JumpIfFalseP  -> {t:04}"),
        Instr::JumpIfTruePeek(t) => format!("JumpIfTrueP   -> {t:04}"),

        Instr::BuildList(n) => format!("BuildList     {n:>4}"),
        Instr::BuildDict(n) => format!("BuildDict     {n:>4}"),
        Instr::Index => "Index".into(),
        Instr::SetIndex => "SetIndex".into(),
        Instr::MakeRange(inclusive) => {
            format!("MakeRange     {}", if *inclusive { "..=" } else { ".." })
        }
        Instr::GetIter => "GetIter".into(),
        Instr::ForIter { slot, exit } => format!("ForIter       slot {slot} exit -> {exit:04}"),
        Instr::BuildStr(n) => format!("BuildStr      {n:>4}"),

        Instr::Call(argc) => format!("Call          {argc:>4}"),
        Instr::Closure(i) => format!("Closure       {i:>4} ({})", constant_repr(chunk, *i)),
        Instr::Return => "Return".into(),
    }
}

/// A short rendering of `constants[idx]` for inline display.
fn constant_repr(chunk: &Chunk, idx: u16) -> String {
    match chunk.constants.get(idx as usize) {
        Some(Constant::Int(n)) => n.to_string(),
        Some(Constant::Float(f)) => format!("{f}"),
        Some(Constant::Str(s)) => format!("{s:?}"),
        None => "<bad const>".into(),
    }
}
